name: mov
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  build:
    web:
      renderer: canvaskit
  
  assets:
    - assets/images/logo.png
    - assets/images/Darkknight.jpg
    - assets/images/Godfather.jpg
    - assets/images/Interstellar.jpg
    - assets/images/Shawshank.jpg
    - assets/images/The_begin.jpg
    - assets/images/ProfileIcon.png
    - assets/images/ChatsIcon.png
    - assets/images/avatar.jpg
  fonts:
    - family: CyGrotesk
      fonts:
        - asset: assets/fonts/CyGrotesk-WideDemi.otf
          weight: 700  
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700  
        - asset: assets/fonts/Onest-SemiBold.ttf
          weight: 600  
